### ISSUE TITLE
Investigate Fedora 4 upgrade and develop stories

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon-planning#4]
_From @davidschober on June 8, 2016 22:10_

Do investigation into Fedora 4 upgrade and develop stories that can be completed in the next sprint cycles.
### Done looks like:

We have a series of technical stories that can be organized with POs.

_Copied from original issue: avalonmediasystem/avalon#847_

**Comment by jlhardes** [comment]
As far as the metadata goes for the Fedora 4 upgrade, the goal is to bring over the special data streams of metadata we’ve created as they are (descriptive, display, sections, etc) so nothing really special needs to happen there, we just need to make sure they all make it (which so far from what I’ve seen after running the first step of fedora-migrate, they do make it). 

Fedora-specific properties from RELS-EXT data stream should be mapped in the second step of the fedora-migrate gem that we haven’t taken yet. I would expect to see fedora: namespaced RDF properties on objects that mirror the RDF XML for models and relations-external on an object in F3 (so the top-level object should have isMemberOfCollection, hasModel and child objects are going to have the isPartOf and hasModel properties). 

I don’t know if we’ll see the relations from projecthydra mapped over, though (hasModelVersion, hasPermalink, isGovernedBy). That will be something to check. It seems like maybe they might all come over from what I’m seeing here (https://github.com/projecthydra-labs/fedora-migrate/blob/master/lib/fedora_migrate/rels_ext_datastream_mover.rb) since this script doesn’t seem to care what the predicates and objects are, it just grabs them and adds them in. So hopefully everything in RELS-EXT is mapped to RDF properties and that is not a data stream that has to be kept.

The DC data stream is not coming over yet, but it could be mapped over as RDF properties on the F4 object. I don't know if fedora-migrate is doing this though as part of the second step so that will also be something to check.

**Comment by joncameron** [comment]
Schedulee for swarm on 06/22
